name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:


# Cancel already running ci on a new push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '>=3.13'

      - name: Install meson and ninja
        run: pip install meson ninja

      - name: Setup MSVC
        if: ${{ matrix.os=='windows-latest' }}
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Configure (debug)
        run: meson setup bin

      - name: Compile and run tests (debug)
        run: meson test -C bin

      - name: Configure (relese)
        run: meson setup bin --wipe --buildtype release

      - name: Compile and run tests (relese)
        run: meson test -C bin